layout_spectrum: 0.021276908433157028
typography_spectrum: 0.27819522407283953
color:
  lightness: 0.2537915609859963
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  saturation: 0.38472757075267777
  brandStrength: 0.7493015086316125
  rhythmicContrast: 0.020934444026708014
coverPrefs:
  filter: false
name: Artist Page
analytics:
  google: UA-31484906-1
purpose:
  - type: external
    url: 'http://thegrid.ai/teacher-page'
    label: Professional
  - type: external
    label: 138 Exposed
    url: 'http://138.exposed'
github: true
description: BlankArt Collection
author:
  name: PB
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3485ee5c-34b5-4216-9932-32f4fedfa634.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3485ee5c-34b5-4216-9932-32f4fedfa634.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: 138 The Campaign
    url: 'https://138.exposed'
    type: external
  - name: 138 Manual
    url: 'https://b318k.tumblr.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1ade943b-d964-46fa-862d-c65f0f343c30.png
content_rating:
  adult: false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c52f500-a758-4076-a669-35d2908e5fa1.png
title: Artist Page
opengraph: {}
url: 'https://thegrid.ai/blankart/'
