layout_spectrum: 0.5894241475419021
typography_spectrum: 0.6280136763932423
color:
  lightness: 0.6034232028635532
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  saturation: 0.7452646444718547
  brandStrength: 0.13709088419859142
  rhythmicContrast: 0.17912042464461583
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph: {}
analytics:
  google: UA-31484906-1
author:
  name: PB
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c52f500-a758-4076-a669-35d2908e5fa1.png
name: Artist Page
url: 'https://thegrid.ai/blankart/'
navigation:
  - name: 138 The Campaign
    url: 'https://138.exposed'
    type: external
  - name: 138 Manual
    url: 'https://b318k.tumblr.com'
    type: external
  - name: Berlin Oberbaumbrücke
    id: 785ec768-20be-41d2-a30d-1154a9b30a90
    type: content
  - name: 138 system in football
    url: 'https://thegrid.ai/138sessions/?cache=no'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1ade943b-d964-46fa-862d-c65f0f343c30.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Artist Page
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3485ee5c-34b5-4216-9932-32f4fedfa634.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3485ee5c-34b5-4216-9932-32f4fedfa634.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: BlankArt Collection
purpose:
  - type: external
    url: 'http://thegrid.ai/teacher-page'
    label: Professional
  - type: external
    label: 138 Exposed
    url: 'http://138.exposed'
